const pathways = [
  {
    id: "aHd3mnf2uw8Ixx7Lp8Ys",
    name: "Plan my Day",
    description: "A simple process to help you focus on what matters most.",
    duration: "3 min",
    time: "Morning",
    emoji: "📜",
    autoPlayMusic: false,
    background: backgroundCover,
    steps: [
      {
        question: "What is the most important task for today?",
        context: "Write down the absolute must for today, 1 main FROG.",
        timer: 30,
        currentStep: 1,
        buttonText: "Next",
        minText: 5,
        responseType: "text",
        allowSkip: false,
        autoplay: false,
      },
      {
        question: "List 2 bonus tasks for today.",
        context: "These are important but not as much as the FROG.",
        timer: 45,
        currentStep: 2,
        buttonText: "Next",
        minText: 10,
        responseType: "text",
        allowSkip: false,
        autoplay: false,
      },
      {
        question: "Add 2 more extra tasks that are nice to have.",
        context:
          "These DONT add pressure! They are fun extras if I want to have fun.",
        timer: 30,
        currentStep: 3,
        buttonText: "Complete",
        minText: 10,
        responseType: "text",
        allowSkip: true,
        autoplay: false,
      },
    ],
  },
  {
    id: "LiuGGIFtC38QfzZp93MP",
    name: "Deep Work",
    description:
      "Get 80% of your daily work done in just 90 minutes of laser focused time.",
    duration: "90 min",
    time: "Morning",
    emoji: "🧘",
    background: backgroundCover,
    steps: [
      {
        question:
          "Remove all possible distractions, all notifications off and all people OFF. Tell everyone you are getting into BEAST MODE.",
        context: "this should be a checklist",
        timer: 30,
        currentStep: 1,
        buttonText: "Next",
        minText: 0,
        responseType: "text",
        allowSkip: true,
        autoplay: false,
      },
      {
        question: "Get your FROG READY.",
        context:
          "POTENTIAL TASK: LINKING OF PATHWAYS, LIKE NOW I NEED TO LINK FIND MY PRIORITIES TASK HERE. OR THE RESULT OF IT?? THINK ABOUT THIS! DENI",
        timer: 10,
        currentStep: 2,
        buttonText: "Next",
        minText: 0,
        responseType: "text",
        allowSkip: true,
      },
      {
        question: "Focus Session #1",
        context:
          "This is type nothing? you just need to do something, maybe timer will be in focus with bonus reminders? or somthn that you might require",
        timer: 60 * 60,
        currentStep: 3,
        buttonText: "Next",
        minText: 0,
        responseType: "text",
      },
      {
        question:
          "Small Break, Get up and stretch, drink water and juggle with balls. Get hyped and ready to complete a tough session!",
        context: "probably checklist again",
        timer: 5 * 60,
        currentStep: 3,
        buttonText: "Next",
        minText: 0,
        responseType: "text",
      },
      {
        question: "Focus Session #2",
        context:
          "This is type nothing? you just need to do something, maybe timer will be in focus with bonus reminders? or somthn that you might require",
        timer: 60 * 60,
        currentStep: 3,
        buttonText: "Next",
        minText: 0,
        responseType: "text",
      },
    ],
  },
  {
    id: "LiuGGIFtC38QfzZp93MP",
    name: "Reflect on Learning",
    description: "Learn by reflection",
    duration: "5 min",
    time: "Night",
    emoji: "📖",
    autoPlayMusic: true,
    background: backgroundCover,
    steps: [
      {
        question: "What new thing did you learn today?",
        context: "Write down at least 1 thing.",
        timer: 60,
        currentStep: 1,
        buttonText: "Next",
        minText: 20,
        responseType: "text",
        allowSkip: false,
        autoplay: false,
      },
      {
        question:
          "Reflect on how you applied yesterday's learning in today's activities.",
        context:
          "Think of something that i have applied today that i learned in a previous session, and try to note what specifically i did and from where i learned it.",
        timer: 150,
        currentStep: 2,
        buttonText: "Next",
        minText: 15,
        responseType: "text",
        allowSkip: true,
      },
    ],
  },
];
